try:
    raise InvalidAccountNameError("test_123", "test_type")

except Exception as e:
    print(e)
